# -*- coding: utf-8 -*-
"""Recommender

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oLwNUTjq9w4cRFuK084mn7nXQRqUKrS_
"""

import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

songs_data = pd.read_csv("spotify_millsongdata.csv")

songs_data["artist"] = songs_data["artist"].fillna("")
songs_data["song"] = songs_data["song"].fillna("")

combined_features = songs_data["artist"] + " " + songs_data["song"]

vectorizer = TfidfVectorizer()
feature_vectors = vectorizer.fit_transform(combined_features)

def recommend_songs(song_name: str, top_n: int = 10):
    list_of_all_titles = songs_data["song"].tolist()

    find_close_match = difflib.get_close_matches(song_name, list_of_all_titles)

    if not find_close_match:
        return {"error": "Song not found"}

    close_match = find_close_match[0]
    index_of_song = songs_data[songs_data.song == close_match].index[0]

    similarity_score = list(
        enumerate(cosine_similarity(feature_vectors[index_of_song], feature_vectors)[0])
    )

    sorted_similar_songs = sorted(similarity_score, key=lambda x: x[1], reverse=True)

    recommendations = []
    i = 1
    for song in sorted_similar_songs:
        index = song[0]
        if i <= top_n:
            recommendations.append({
                "rank": i,
                "song": songs_data.iloc[index]["song"],
                "artist": songs_data.iloc[index]["artist"]
            })
            i += 1

    return recommendations